services:
  - type: web
    name: aklatak-backend
    env: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3000
